const GLOBAL_ROLES = Object.freeze({
    ADMIN: "ADMIN",
    COUNTRY_DIRECTOR: "COUNTRY_DIRECTOR",
    USER: "USER"
});

const HR = Object.freeze({
    HEAD: "HR_HEAD",
    SPECIALIST: "HR_SPECIALIST",
    MEMBER: "HR_MEMBER"
});

const IT = Object.freeze({
    DIRECTOR: "IT_DIRECTOR",
    COUNTRY_MANAGER: "IT_COUNTRY_MANAGER",
    WMS_SPECIALIST: "IT_WMS_SPECIALIST",
    INFRA_ADMIN: "IT_INFRA_ADMIN",
    ENGINEER: "IT_ENGINEER",
    TMS_SPECIALIST: "IT_TMS_SPECIALIST",
    PROJECT_MANAGER: "IT_PROJECT_MANAGER"
});

const ENGINEERING = Object.freeze({
    HEAD: "ENG_HEAD",
    ENGINEER: "ENG_ENGINEER"
});

const FACILITIES = Object.freeze({
    MANAGER: "FAC_MANAGER",
    TEAM_LEADER: "FAC_LEADER"
});

const OPERATIONS = Object.freeze({
    HEAD: "OPS_HEAD",
    MANAGER: "OPS_MANAGER",
    SPECIALIST: "OPS_SPECIALIST",
    ADMIN: "OPS_ADMIN"
});

const SALES = Object.freeze({
    DIRECTOR: "SALES_DIRECTOR",
    MANAGER: "SALES_MANAGER",
    REPRESENTATIVE: "SALES_REP",
    SPECIALIST: "SALES_SPECIALIST"
});

const TRANSPORT = Object.freeze({
    HEAD: "TRANSPORT_HEAD",
    FORWARDER_DOMESTIC: "FORWARDER_DOMESTIC",
    FORWARDER_INTERNATIONAL: "FORWARDER_INTERNATIONAL",
    GROUPAGE_NETWORK_MANAGER: "GROUPAGE_MANAGER",
    FLEET_MANAGER: "FLEET_MANAGER",
    MEMBER: "TRANSPORT_MEMBER"
});

const FINANCE = Object.freeze({
    CONTROLLER: "FIN_CONTROLLER",
    ANALYST: "FIN_ANALYST",
});

const KAM = Object.freeze({
    DIRECTOR: "KAM_DIRECTOR",
    MANAGER: "KAM_MANAGER",
    READ_WRITE: "KAM_RW",
    READ_ONLY: "KAM_RO",
});

const CONTROLLING = Object.freeze({
    MANAGER: "CTRL_MANAGER",
    ANALYST: "CTRL_ANALYST"
});

module.exports = {
    GLOBAL_ROLES,
    DEPARTMENTS: {
        HR,
        IT,
        ENGINEERING,
        FACILITIES,
        OPERATIONS,
        SALES,
        TRANSPORT,
        FINANCE,
        KAM,
        CONTROLLING,
    }
};